apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 730909931895.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: 730909931895.dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: c9d0b56a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
